---
driver:
  name: vagrant
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-10.04
    run_list:
      - recipe[apt]
  - name: ubuntu-10.04-i386
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04-i386
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04-i386
    run_list:
      - recipe[apt]
  - name: centos-6.5
    run_list:
      - recipe[yum]
  - name: centos-6.5-i386
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[threatstack::default]
    attributes:
      threatstack:
        deploy_key: <%= ENV['TS_DEPLOY_KEY'] %>
