AllCops:
  Exclude:
    - metadata.rb
    - Rakefile
    - vendor/**/*
    - spec/**/*
    - Gemfile

Style/ConditionalAssignment:
  Enabled: false

LineLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
