language: ruby
bundler_args: "--without system_tests"
script:
- bundle exec rake
cache: bundler
sudo: required
rvm:
- 2.2
before_install:
- gem update --system 2.4.8
- gem --version
env:
- CHEF_VERSION="= 12.4.1"
- CHEF_VERSION="= 12.9.41"
- CHEF_VERSION="= 12.14.89"

notifications:
  slack:
    secure: Kqp/g7ta+JzAklXhTIl+ZU+FqrdXJe7DNWuqDZXec4YLLB9pFR1MpUyW1kx+WBcb7Fc//w4Q+1NLn02Slg9ay1xkRkNVi1UInUk89ocqwPbsmESA/690fnRba+C7mW/6D3Z+C7AMPQeZszhcRVzX1xrH3b3xlvLMvyFk/UnQOMU=
